import tap from 'tap'

import { formatNumberOrdinals } from '../formatNumberOrdinals.js'

await tap.test('utils/formatNumberOrdinals', async (t) => {
  t.equal(formatNumberOrdinals(1), '1st')
  t.equal(formatNumberOrdinals(2), '2nd')
  t.equal(formatNumberOrdinals(3), '3rd')
  t.equal(formatNumberOrdinals(4), '4th')
  t.equal(formatNumberOrdinals(5), '5th')
  t.equal(formatNumberOrdinals(6), '6th')
  t.equal(formatNumberOrdinals(7), '7th')
  t.equal(formatNumberOrdinals(8), '8th')
  t.equal(formatNumberOrdinals(9), '9th')
  t.equal(formatNumberOrdinals(10), '10th')
  t.equal(formatNumberOrdinals(11), '11th')
  t.equal(formatNumberOrdinals(12), '12th')
  t.equal(formatNumberOrdinals(13), '13th')
  t.equal(formatNumberOrdinals(14), '14th')
  t.equal(formatNumberOrdinals(15), '15th')
  t.equal(formatNumberOrdinals(16), '16th')
  t.equal(formatNumberOrdinals(17), '17th')
  t.equal(formatNumberOrdinals(18), '18th')
  t.equal(formatNumberOrdinals(19), '19th')
  t.equal(formatNumberOrdinals(20), '20th')
  t.equal(formatNumberOrdinals(21), '21st')
  t.equal(formatNumberOrdinals(22), '22nd')
  t.equal(formatNumberOrdinals(23), '23rd')
  t.equal(formatNumberOrdinals(24), '24th')
  t.equal(formatNumberOrdinals(25), '25th')
  t.equal(formatNumberOrdinals(26), '26th')
  t.equal(formatNumberOrdinals(27), '27th')
  t.equal(formatNumberOrdinals(28), '28th')
  t.equal(formatNumberOrdinals(29), '29th')
  t.equal(formatNumberOrdinals(30), '30th')
  t.equal(formatNumberOrdinals(31), '31st')
  t.equal(formatNumberOrdinals(32), '32nd')
  t.equal(formatNumberOrdinals(33), '33rd')
  t.equal(formatNumberOrdinals(34), '34th')
  t.equal(formatNumberOrdinals(35), '35th')
  t.equal(formatNumberOrdinals(501), '501st')
  t.equal(formatNumberOrdinals(502), '502nd')
  t.equal(formatNumberOrdinals(503), '503rd')
  t.equal(formatNumberOrdinals(504), '504th')
  t.equal(formatNumberOrdinals(571), '571st')
  t.equal(formatNumberOrdinals(572), '572nd')
  t.equal(formatNumberOrdinals(573), '573rd')
  t.equal(formatNumberOrdinals(574), '574th')
})
